version: "3.9"
services:
  db:
    image: postgres
    container_name: capybara_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: capybara
      POSTGRES_PASSWORD: capybara
    volumes:
      - capybara_pg:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: capybara_server
    restart: always
    ports:
      - "9999:9000"
    environment:
      PORT: 9000
      DB_HOST: db
      DB_USER: capybara
      DB_PASSWORD: capybara
      DB_NAME: capybara
      DB_PORT: 5432
      AWS_ACCESS_KEY_ID: AKIATWPTWBO6YGJTUUGY
      AWS_SECRET_ACCESS_KEY: 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
      AWS_S3_REGION: eu-west-3
      AWS_S3_BUCKET_NAME: internshipapi-storage
    depends_on:
      - db
    links:
      - db
volumes:
  capybara_pg:
