version: "3.8"
services:
  db:
    image: postgres
    container_name: capybara_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: capybara
      POSTGRES_PASSWORD: capybara
    volumes:
      - capybara_pg:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: capybara@test.com
      PGADMIN_DEFAULT_PASSWORD: capybara
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  capybara_pg:
  pgadmin-data: