name: Tag Pull Request Commit

on: [push, pull_request]

jobs:
    tag:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Git
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "Capybara"

            - name: Get version from pull request title
              id: version
              run: echo "$(echo ${{ github.event.pull_request.title }} | grep -o -P '(\d+\.\d+\.\d+)')" >> "$COMMIT_VERSION"

            - name: Create tag
              run: |
                  echo "version=$COMMIT_VERSION"
              #   git tag -a "${{ steps.version.outputs.version }}" -m "Tag for PR #${{ github.event.number }}"
              #   git push origin "${{ steps.version.outputs.version }}"
